---
title: "PM Chemical Analysis"
author: "Timothy Smyth"
date: "2025-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Clear the environment and import required packages

```{r}
rm(list = ls(all.names = TRUE)) # clears global environ.

library(tidyverse)
library(ggplot2)
library(RColorBrewer)
```

### Import and format PM chemistry data

```{r}
PM_Chemistry <- read.csv('Mass Fraction Data.csv')
PM_Chemistry <- data.frame(PM_Chemistry[-1], row.names = PM_Chemistry$Chemical.Component)

# Classify chemical components into specific chemical class
Organic_Carbon <- c('Organic Carbon')
Elemental_Carbon <- c('Elemental Carbon')
Unknown <- c('Unknown')
Anionics <- c('Chloride', 'Fluoride', 'Bromide', 'Nitrate', 'Nitrite', 'Phosphate', 'Sulfate')
Inorganics <- c('Ti', 'Cr', 'Ni', 'Zn', 'As', 'Se', 'Cd', 'Sb', 'Pb', 
                'L', 'Na', 'K', 'Rb', 'Cs', 'Be', 'Mg', 'Ca', 'Sr', 'Ba',
                'V', 'Mn', 'Fe', 'Co', 'Cu', 'Mo', 'Ag', 'W', 
                'Y', 'La', 'Ce', 'Nd', 'Sm', 'Gd', 'Tb', 'Dy', 
                'Al', 'Ge', 'Sn', 'Si', 'P', 'S',  'Tl', 'Bi')

# Condense chemical class assignments into a single list and assign proper names
Chemical_lists <- list(Organic_Carbon, Elemental_Carbon, Unknown, Anionics, Inorganics)

names(Chemical_lists) <- c('Organic_Carbon', 'Elemental_Carbon', 'Unknown', 'Anionic Species', 'Inorganic Elements')

# Determine the total mass fraction for each chemical class
Season_Chemistry_Data <- lapply(names(Chemical_lists), function(Single_Class){
  
  # Isolate mass fraction data for each component within the current chemical class
  PM_Chemistry_Subset <- PM_Chemistry[rownames(PM_Chemistry) %in% unlist(Chemical_lists[Single_Class]), ]

  # Sum the mass fraction values to get a single value for each class
  Sums <- data.frame(colSums(PM_Chemistry_Subset)) %>% setNames(c(Single_Class))
  
})

# Combine data into single location
Season_Chemistry_Data <- do.call(cbind, Season_Chemistry_Data)

# Set rownames to column
Season_Chemistry_Data <- Season_Chemistry_Data %>% rownames_to_column()

# Pivot data longer
Season_Chemistry_Data <- Season_Chemistry_Data %>% pivot_longer(cols = colnames(Season_Chemistry_Data)[-1], 
                                                                values_to = 'Mass_Fraction', 
                                                                names_to = 'Analyte')

# Set analytes and particle season to factor
Season_Chemistry_Data$Analyte <- factor(Season_Chemistry_Data$Analyte, 
                                        levels = c('Unknown', 
                                                   'Inorganic Elements', 'Anionic Species', 
                                                   'Elemental_Carbon', 'Organic_Carbon'))

Season_Chemistry_Data$rowname <- factor(Season_Chemistry_Data$rowname, 
                                        levels = c('Winter', 'Spring', 'Summer', 'Fall'))
```

### Create Figure 2A

```{r}
png(filename = "Figure 2A.png", width = 1000, height = 400)

ggplot(Season_Chemistry_Data, 
       aes(y = rowname, x = Mass_Fraction, fill = Analyte)) +
  
  geom_bar(position = "stack", 
           stat = "identity", 
           width = 0.5) + 
  
  scale_fill_manual(values = c('grey50', 
                               'tomato3', 'orange', 
                               'purple', 'blue')) +
  
  labs(x = "Mass Fraction (%)", y = NULL) +
  
  theme_bw() +
  
  theme(axis.title.x = element_text(size = 20, face = 'bold'), 
        axis.text.y = element_text(size = 20), 
        panel.grid.major = element_blank(),
        axis.text.x = element_text(size = 20))

dev.off()
```

### Create Figure 2B-E

```{r}
# Isolate inorganic element data
Inorganic_data <- PM_Chemistry[rownames(PM_Chemistry) %in% unlist(Inorganics), ] %>% 
  t() %>% 
  data.frame()

# Assign season and output panel information
Season <- c('Winter', 'Spring', 'Summer', 'Fall')
Panel <- c('B', 'C', 'D', 'E')

# Create not in function
`%ni%` <- negate(`%in%`)

# Create pie charts for inorganic mass fraction data
Inorganic_charts <- lapply(c(1:4), function(Index){
  
  # Isolate inorganic data
  Inorganic_data_subset <- Inorganic_data[Season[Index], ]
  
  # Isolate top elements and not top elements
  top_elements <- Inorganic_data_subset[, c('Ca', 'K', 'Fe', 'Na', 'P', 'Zn', 'Mg', 'Mn', 'S')]
  not_top_elements <- Inorganic_data_subset[, colnames(Inorganic_data_subset) %ni% colnames(top_elements)]
  Other <- data.frame(Other = rowSums(not_top_elements), row.names = Season[Index])
  
  # Combine top element data and total value of other elements
  Inorganic_data_subset <- cbind(top_elements, Other)
  
  # Calculate row sums of data to get percent value
  percent_value <- rowSums(Inorganic_data_subset)
  
  # Set rowname to column
  Inorganic_data_subset <- Inorganic_data_subset %>% rownames_to_column()
  
  # Pivot data longer
  Inorganic_data_subset <- Inorganic_data_subset %>% 
    pivot_longer(cols = colnames(Inorganic_data_subset)[-1],
                 values_to = 'Mass_Fraction',
                 names_to = 'Analyte')
  
  # Set analytes to factor
  Inorganic_data_subset$Analyte <- factor(Inorganic_data_subset$Analyte, 
                                          levels = c('Ca', 'K', 'Fe', 'Na', 'P', 'Zn', 'Mg', 'Mn', 'S', 'Other'))
  
  # Create pie charts of analyte mass fraction data
  plot <- ggplot(Inorganic_data_subset, 
                 aes(x = "", y = Mass_Fraction, fill = Analyte)) +
    
    geom_bar(stat = "identity", width = 1) +
    
    coord_polar("y", start = 0) +
    
    labs(title = paste0(Season[Index], '\n Total = ', round(percent_value, 2), '%'), x = NULL, y = NULL) + 
    
    theme_bw() +
    
    theme(axis.line = element_line(colour = "white"),
          panel.grid.major = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(size = 16, hjust = 0.5),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank()) +
    
  scale_fill_brewer(palette = 'Set3') +
  
  png(filename = paste0("Figure 2", Panel[Index], ".png"), width = 400, height = 400)
  
  print(plot)
  
  dev.off()
  
  plot
  
})
```

### Create Figure 2F-I

```{r}
# Isolate anionic species data
Anionics_data <- PM_Chemistry[rownames(PM_Chemistry) %in% unlist(Anionics), ] %>% 
  t() %>% 
  data.frame()

# Assign output panel information
Panel <- c('F', 'G', 'H', 'I')

# Create pie charts for inorganic mass fraction data
Anionics_charts <- lapply(c(1:4), function(Index){
  
  # Isolate anionic data
  Anionics_data_subset <- Anionics_data[Season[Index], ]
  
  # Calculate row sums of data to get percent value
  percent_value <- rowSums(Anionics_data_subset)
  
  # Set rowname to column
  Anionics_data_subset <- Anionics_data_subset %>% rownames_to_column()
  
  # Pivot data longer
  Anionics_data_subset <- Anionics_data_subset %>% 
    pivot_longer(cols = colnames(Anionics_data_subset)[-1],
                 values_to = 'Mass_Fraction',
                 names_to = 'Analyte')
  
  # Set analytes to factor
  Anionics_data_subset$Analyte <- factor(Anionics_data_subset$Analyte, 
                                         levels = c('Chloride', 'Fluoride', 
                                                    'Bromide', 'Nitrate', 
                                                    'Nitrite', 'Phosphate', 
                                                    'Sulfate'))
  
  # Create pie charts of analyte mass fraction data
  plot <- ggplot(Anionics_data_subset, 
                 aes(x = "", y = Mass_Fraction, fill = Analyte)) +
    
    geom_bar(stat = "identity", width = 1) +
    
    coord_polar("y", start = 0) +
    
    labs(title = paste0(Season[Index], '\n Total = ', round(percent_value, 2), '%'), x = NULL, y = NULL) + 
    
    theme_bw() +
    
    theme(axis.line = element_line(colour = "white"),
          panel.grid.major = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(size = 16, hjust = 0.5),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank()) +
    
    scale_fill_manual(values = c('lightblue', 'violet', 
                                 'tomato', 'lightgreen', 
                                 'steelblue3', 'lightslateblue', 'peachpuff'))
  
  png(filename = paste0("Figure 2", Panel[Index], ".png"), width = 400, height = 400)
  
  print(plot)
  
  dev.off()
  
  plot
  
})
```